<a href="https://colab.research.google.com/github/RisalahNaufal/DATA-MINING_Perancangan-Website-Pemilihan-Obat-Menggunakan-Algoritma-Naive-Bayes/blob/main/drugg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import pickle

In [ ]:
data = pd.read_csv('drug200.csv')
data.head(15)

Age Sex      BP Cholesterol  Na_to_K   Drug
0    23   F    HIGH        HIGH   25.355  DrugY
1    47   M     LOW        HIGH   13.093  drugC
2    47   M     LOW        HIGH   10.114  drugC
3    28   F  NORMAL        HIGH    7.798  drugX
4    61   F     LOW        HIGH   18.043  DrugY
5    22   F  NORMAL        HIGH    8.607  drugX
6    49   F  NORMAL        HIGH   16.275  DrugY
7    41   M     LOW        HIGH   11.037  drugC
8    60   M  NORMAL        HIGH   15.171  DrugY
9    43   M     LOW      NORMAL   19.368  DrugY
10   47   F     LOW        HIGH   11.767  drugC
11   34   F    HIGH      NORMAL   19.199  DrugY
12   43   M     LOW        HIGH   15.376  DrugY
13   74   F     LOW        HIGH   20.942  DrugY
14   50   F  NORMAL        HIGH   12.703  drugX

In [ ]:
# To get the number of rows and columns in the dataset
data.shape

(200, 6)

In [ ]:
## Labelling 0 & 1 for Sex
data.Sex=data.Sex.map({'M':1,'F':0})

## Labelling 0 & 1 for Blood Pressure
data.BP=data.BP.map({'HIGH':2,'NORMAL':1,'LOW':0})

## Labelling 0 & 1 for Cholesterol
data.Cholesterol=data.Cholesterol.map({'HIGH':1,'NORMAL':0})

## Labelling 0 & 1 for Drug
data.Drug=data.Drug.map({'drugC':4,'drugB':3,'drugA':2,'drugX':1,'DrugY':0})

In [ ]:
data.head()

Age  Sex  BP  Cholesterol  Na_to_K  Drug
0   23    0   2            1   25.355     0
1   47    1   0            1   13.093     4
2   47    1   0            1   10.114     4
3   28    0   1            1    7.798     1
4   61    0   0            1   18.043     0

In [ ]:
DATACSV = data.to_csv('drug2000.csv')

In [ ]:
# from sklearn.preprocessing import LabelEncoder
# enc = LabelEncoder()
# target = 'Drug'
# encode = ('Sex','BP','Cholesterol')
# data.head()

In [ ]:
# for col in encode:
#   dummy = pd.get_dummies(data[col],prefix=col)
#   data = pd.concat([data,dummy], axis=1)
#   del data[col]

In [ ]:
# data

In [ ]:
# target_mapper = {'DrugY':0, 'drugX':1, 'drugC':2}

In [ ]:
# def target_encode(val):
#   return target_mapper[val]

In [ ]:
# data['Drug'] = data['Drug'].apply(target_encode)

In [ ]:
# To get the statistical measures of the data
data.describe()

Age         Sex          BP  Cholesterol     Na_to_K        Drug
count  200.000000  200.000000  200.000000   200.000000  200.000000  200.000000
mean    44.315000    0.520000    1.065000     0.515000   16.084485    1.060000
std     16.544315    0.500854    0.839224     0.501029    7.223956    1.270619
min     15.000000    0.000000    0.000000     0.000000    6.269000    0.000000
25%     31.000000    0.000000    0.000000     0.000000   10.445500    0.000000
50%     45.000000    1.000000    1.000000     1.000000   13.936500    1.000000
75%     58.000000    1.000000    2.000000     1.000000   19.380000    2.000000
max     74.000000    1.000000    2.000000     1.000000   38.247000    4.000000

In [ ]:
# To get details of the outcome column
data['Drug'].value_counts()

0    91
1    54
2    23
4    16
3    16
Name: Drug, dtype: int64

In [ ]:
# separating the data and labels
X = data.drop(columns = 'Drug', axis=1)
Y = data['Drug']

# DT

In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()

In [ ]:
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import GridSearchCV
#Splid data dengan RepeatedStratifiedKFold dan Tuning Hyperparameter dengan GridSearchCV
cv_method = RepeatedStratifiedKFold(n_splits=10,  n_repeats=3, random_state=999)

param_grid_clf = {'criterion':['gini', 'entropy', 'log_loss'], 'max_depth':np.arange(1,10),}
scoring_metrics = ['accuracy', 'f1_macro']

gs_clf = GridSearchCV(estimator=clf, param_grid=param_grid_clf, cv=cv_method,verbose=1, scoring=scoring_metrics, refit='accuracy')
gs_clf.fit(X,Y)

# Menampilkan parameter terbaik dan skor terbaik untuk akurasi dan F1-score macro
print("Best Parameters (Accuracy):", gs_clf.best_params_)
print("Best Score (Accuracy):", gs_clf.best_score_)
print("Best Score (F1 Macro):", gs_clf.cv_results_['mean_test_f1_macro'][gs_clf.best_index_])

Fitting 30 folds for each of 27 candidates, totalling 810 fits
Best Parameters (Accuracy): {'criterion': 'gini', 'max_depth': 4}
Best Score (Accuracy): 0.9900000000000001
Best Score (F1 Macro): 0.9822977646135541


# KNN

In [ ]:
#Tuning Hyperparameter KNN otomatis dengan GridSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()
param_grid={'n_neighbors':np.arange(5,50),'weights':['distance','uniform']}
scoring_metrics = ['accuracy', 'f1_macro']

gscv=GridSearchCV(model, param_grid=param_grid, scoring=scoring_metrics, cv=5, refit='accuracy')
gscv.fit(X,Y)

# Menampilkan parameter terbaik dan skor terbaik untuk akurasi dan F1-score macro
print("Best Parameters (Accuracy):", gscv.best_params_)
print("Best Score (Accuracy):", gscv.best_score_)
print("Best Score (F1 Macro):", gscv.cv_results_['mean_test_f1_macro'][gscv.best_index_])

Best Parameters (Accuracy): {'n_neighbors': 14, 'weights': 'distance'}
Best Score (Accuracy): 0.7300000000000001
Best Score (F1 Macro): 0.5513459173459173


In [ ]:
#Split the data into train and test
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, stratify=Y, random_state=2)
print(X.shape, X_train.shape, X_test.shape)

(200, 5) (160, 5) (40, 5)


In [ ]:
# Create KNN classifier
knn = KNeighborsClassifier(n_neighbors = 3)
# Fit the classifier to the data
knn.fit(X_train,Y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
#show first 5 model predictions on the test data
knn.predict(X_test)[0:5]

array([2, 3, 0, 1, 0])

In [ ]:
#check accuracy of our model on the test data
knn.score(X_test, Y_test)

0.775

In [ ]:
# Accuracy score on the training data
X_train_prediction = knn.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

print('Accuracy score of the training data : ', training_data_accuracy)

# Accuracy score on the test data
X_test_prediction = knn.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the training data :  0.8875
Accuracy score of the test data :  0.775


#NB

In [ ]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
#Split data dengan RepeatedStratifiedKFold dan Tuning Hyperparameter dengan GridSearchCV
cv_method = RepeatedStratifiedKFold(n_splits=10,  n_repeats=3, random_state=999)

param_grid_nb = {'var_smoothing': np.logspace(0,-9, num=100)}
scoring_metrics = ['accuracy', 'f1_macro']

gs_NB = GridSearchCV(estimator=model, param_grid=param_grid_nb, cv=cv_method,verbose=1,scoring=scoring_metrics, refit='accuracy')
gs_NB.fit(X,Y)

# Menampilkan parameter terbaik dan skor terbaik untuk akurasi dan F1-score macro
print("Best Parameters (Accuracy):", gs_NB.best_params_)
print("Best Score (Accuracy):", gs_NB.best_score_)
print("Best Score (F1 Macro):", gs_NB.cv_results_['mean_test_f1_macro'][gs_NB.best_index_])

Fitting 30 folds for each of 100 candidates, totalling 3000 fits
Best Parameters (Accuracy): {'var_smoothing': 0.0006579332246575676}
Best Score (Accuracy): 0.9666666666666667
Best Score (F1 Macro): 0.9455176442637742


#SVC

In [ ]:
#Liniear SVC
from sklearn.svm import LinearSVC
import warnings
warnings.filterwarnings('ignore')
#warnings.filterwarnings(action='once')

clf = LinearSVC()


#Splid data dengan RepeatedStratifiedKFold dan Tuning Hyperparameter dengan GridSearchCV
cv_method = RepeatedStratifiedKFold(n_splits=10,  n_repeats=3, random_state=999)
scoring_metrics = ['accuracy', 'f1_macro']

c = np.logspace(start = -15, stop = 1000, base = 1.02)
param_grid = {'C': c}


grid = GridSearchCV(clf, param_grid =param_grid, cv=cv_method, n_jobs=-1, scoring=scoring_metrics, refit='accuracy')
grid.fit(X, Y)

# Menampilkan parameter terbaik dan skor terbaik untuk akurasi dan F1-score macro
print("Best Parameters (Accuracy):", grid.best_params_)
print("Best Score (Accuracy):", grid.best_score_ * 100)
print("Best Score (F1 Macro):", grid.cv_results_['mean_test_f1_macro'][grid.best_index_])

Best Parameters (Accuracy): {'C': 1.687680582634043}
Best Score (Accuracy): 83.0
Best Score (F1 Macro): 0.703217727855768


#Regresi Logistik

In [ ]:
from sklearn.linear_model import LogisticRegression

# Membuat objek Regresi Logistik
clf = LogisticRegression(solver='liblinear')

# Splid data dengan RepeatedStratifiedKFold dan Tuning Hyperparameter dengan GridSearchCV
cv_method = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=999)
scoring_metrics = ['accuracy', 'f1_macro']

# Definisikan rentang hyperparameter yang ingin diuji
c = np.logspace(start=-15, stop=1000, base=1.02)
param_grid = {'C': c}

grid = GridSearchCV(clf, param_grid=param_grid, cv=cv_method, n_jobs=-1, scoring=scoring_metrics, refit='accuracy')
grid.fit(X, Y)

# Menampilkan parameter terbaik dan skor terbaik untuk akurasi dan F1-score macro
print("Best Parameters (Accuracy):", grid.best_params_)
print("Best Score (Accuracy):", grid.best_score_ * 100)
print("Best Score (F1 Macro):", grid.cv_results_['mean_test_f1_macro'][grid.best_index_])


Best Parameters (Accuracy): {'C': 21118.24384789908}
Best Score (Accuracy): 96.66666666666666
Best Score (F1 Macro): 0.9435390846969796


#ANN

In [ ]:
from sklearn.neural_network import MLPClassifier

# Membuat objek MLPClassifier
clf = MLPClassifier()

# Splid data dengan RepeatedStratifiedKFold dan Tuning Hyperparameter dengan GridSearchCV
cv_method = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=999)
scoring_metrics = ['accuracy', 'f1_macro']

# Definisikan rentang hyperparameter yang ingin diuji
hidden_layer_sizes = [(50, 50), (100, 100), (100, 50, 25)]  # Contoh saja, sesuaikan dengan kebutuhan Anda
alpha = [0.0001, 0.001, 0.01]  # Contoh saja, sesuaikan dengan kebutuhan Anda
param_grid = {'hidden_layer_sizes': hidden_layer_sizes, 'alpha': alpha}

grid = GridSearchCV(clf, param_grid=param_grid, cv=cv_method, n_jobs=-1, scoring=scoring_metrics, refit='accuracy')
grid.fit(X, Y)

# Menampilkan parameter terbaik dan skor terbaik untuk akurasi dan F1-score macro
print("Best Parameters (Accuracy):", grid.best_params_)
print("Best Score (Accuracy):", grid.best_score_ * 100)
print("Best Score (F1 Macro):", grid.cv_results_['mean_test_f1_macro'][grid.best_index_])


Best Parameters (Accuracy): {'alpha': 0.01, 'hidden_layer_sizes': (100, 100)}
Best Score (Accuracy): 75.5
Best Score (F1 Macro): 0.615456938285688


#FINAL

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size=0.3, random_state=32)

In [ ]:
from sklearn.naive_bayes import GaussianNB
modelnb = GaussianNB()
modelnb.fit(X_train, y_train)

GaussianNB()

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix

# Prediksi label kelas pada data latih
y_train_pred = modelnb.predict(X_train)

# Menghitung akurasi pada data latih
train_accuracy = accuracy_score(y_train, y_train_pred)
print("Training Accuracy:", round(train_accuracy*100, 2), '%')

# Membuat confusion matrix pada data latih
conf_matrix_train = confusion_matrix(y_train, y_train_pred)
print("Confusion Matrix (Training Data):",)
print(conf_matrix_train)


# Prediksi label kelas pada data test
y_pred = modelnb.predict(X_test)

# Menghitung akurasi
accuracy = accuracy_score(y_test, y_pred)
print("Test Accuracy:", round(accuracy*100, 2),'%')

# Membuat confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

Training Accuracy: 87.86 %
Confusion Matrix (Training Data):
[[47  0  6  3  7]
 [ 1 37  0  0  0]
 [ 0  0 15  0  0]
 [ 0  0  0 11  0]
 [ 0  0  0  0 13]]
Test Accuracy: 80.0 %
Confusion Matrix:
[[21  0  2  2  3]
 [ 5 11  0  0  0]
 [ 0  0  8  0  0]
 [ 0  0  0  5  0]
 [ 0  0  0  0  3]]


In [ ]:
data = [[47, 1, 0, 1, 13.093]]
print(modelnb.predict(data))

[4]


In [ ]:
import pickle
# now you can save it to a file
file = 'ML_NB_DRUG3.pkl'
with open(file, 'wb') as f:
    pickle.dump(modelnb, f)